name: py35
dependencies:
  - pip=8.1.1=py35_0
  - pip:
    - docker-py> = 1.9.0
    - docutils >= 0.12
    - pymongo >= 3.2.2
    - PyYAML >= 3.11
    - web.py >= 0.40.dev0
    - pylti >= 0.4.1
    - watchdog >= 0.8.3
    - msgpack-python >= 0.4.7
    - pyzmq >= 15.3.0
    - Pygments >= 2.0.2
    - sh >= 1.11
